<a href="https://colab.research.google.com/github/veetcoder/pytorch-notebook/blob/main/Tensors_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import torch

In [46]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [47]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [48]:
# Addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [49]:
# Substraction
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [50]:
# Substraction longhand
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [51]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [52]:
# Multiplication longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [53]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [54]:
# Division longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [55]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [56]:
# Remainder Modulus longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [57]:
# Exponents
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [58]:
# Exponents longhand
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [59]:
# Another way to do a math operation
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [60]:
# Reassigment
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [62]:
tensor_a

tensor([ 6,  8, 10, 12])