<a href="https://colab.research.google.com/github/veetcoder/pytorch-notebook/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [4]:
# Python lists
my_list = [[1, 2, 3, 4], [5, 6, 7, 8]]
my_list

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [5]:
# Numpy arrays
np1 = np.random.rand(3, 4)
np1

array([[0.72021881, 0.21008668, 0.89219104, 0.50182947],
       [0.81609697, 0.76672018, 0.63870555, 0.43166048],
       [0.11093178, 0.15021708, 0.0588742 , 0.04802094]])

In [6]:
np1.dtype

dtype('float64')

In [7]:
# Tensors
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[ 0.4997,  0.3509,  1.7446, -0.6547],
        [-0.3459,  1.5365, -0.0137,  0.2500],
        [-1.9461, -1.6841,  0.0991,  0.1577]])

In [8]:
tensor_3d = torch.randn(2, 3, 4)
tensor_3d

tensor([[[ 1.5594,  0.4254, -0.4117,  0.8374],
         [-0.9491,  0.8902,  1.3768,  2.1552],
         [-0.6012, -0.7347,  0.6308, -1.4898]],

        [[ 0.5359, -0.2231,  0.5384, -0.0437],
         [-0.6340,  0.9846, -0.9013, -1.6488],
         [ 0.4092,  0.8837, -1.8937, -1.5982]]])

In [10]:
tensor_3d_zeroes = torch.zeros(2, 3, 4)
tensor_3d_zeroes

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
tensor_from_np = torch.tensor(np1)
tensor_from_np

tensor([[0.7202, 0.2101, 0.8922, 0.5018],
        [0.8161, 0.7667, 0.6387, 0.4317],
        [0.1109, 0.1502, 0.0589, 0.0480]], dtype=torch.float64)